apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openchoreo

labels:
  - pairs:
      openchoreo.dev/organization: openchoreo

resources:
  # Projects
  - demo-project-1/
  - ecommerce-demo/