apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Project
  - project.yaml
  # Components
  - components/product-api/
  - components/order-api/
  - components/redis-cache/