apiVersion: openchoreo.dev/v1alpha1
kind: Environment
metadata:
  name: development
  namespace: openchoreo
  annotations:
    openchoreo.dev/display-name: Development
    openchoreo.dev/description: Development environment for testing and development
  labels:
    openchoreo.dev/name: development
spec:
  dataPlaneRef: non-prod
  gateway:
    dnsPrefix: dev
  isProduction: false