apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Component Definition
  - component.yaml
  - workload.yaml

  # Component Releases

  # Release Bindings
#  - release-bindings/dev-environment.yaml
