apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Component Definition
  - component.yaml
  - workload.yaml

  # Component Releases
  - releases/greeter-service-20251205-1.yaml

  # Release Bindings
  - release-bindings/greeter-service-development.yaml
