apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openchoreo-platform
  namespace: flux-system
spec:
  interval: 5m
  path: ./platform
  prune: true
  kustomize:
    build: false
  sourceRef:
    kind: GitRepository
    name: openchoreo-gitops
  dependsOn:
    - name: openchoreo-namespace-org