apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openchoreo-projects-release-bindings
  namespace: flux-system
spec:
  interval: 5m
  path: ./projects-release-bindings
  prune: true
  sourceRef:
    kind: GitRepository
    name: openchoreo-gitops
  dependsOn:
    - name: openchoreo-projects